---
exclude: \.idea|tmp/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
            - types-click==7.1.8
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: make test
        language: system
        types_or: [python]
        pass_filenames: false
        require_serial: true
      - id: test-punch-consistency
        name: Test punch format consistency
        entry: make test-punch-consistency
        language: system
        types_or: [python]
        pass_filenames: false
        require_serial: true
